spring.cloud.stream:
  function:
    definition: orderService
  bindings:
    orderService-in-0:
      destination: order-topic
  kafka:
    bindings:
      orderService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092
